#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

RASPBIAN=1

if [ -n "$RASPBIAN" ]; then
  TGT_ARCH=armhf
  DEB_MIRROR=http://mirrordirector.raspbian.org/raspbian/
else
  TGT_ARCH=armel
  DEB_MIRROR=http://http.debian.net/debian
fi
APT_PROXY=http://apt-cache.tomlins.org.uk:3142/

NBD_DEV=/dev/nbd0
BOOT_DEV="$NBD_DEV"p1
ROOT_DEV="$NBD_DEV"p2

IMGFORMAT=qed
SDSIZE=2825M

# Changing these isn't currently supported
WORKDIR=work
OUTDIR=out
